# Generated by Django 5.2.7 on 2025-12-05 17:51

import Post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=30)),
                ('description', models.TextField(default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to=Post.models.image_file_upload_handler)),
            ],
        ),
    ]
