# Generated by Django 5.2.7 on 2025-12-17 15:35

import Post.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0006_post_album_alter_post_image'),
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album.albummodel'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Post.models.image_file_upload_handler),
        ),
    ]
