# Generated by Django 5.2.7 on 2025-12-17 15:38

import Post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0008_alter_post_album_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Post.models.image_file_upload_handler),
        ),
    ]
