# Generated by Django 5.2.7 on 2025-12-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='albumModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=10)),
                ('albumaccess', models.CharField(choices=[('public', 'pub'), ('private', 'pvt')], default='private', max_length=7)),
            ],
        ),
    ]
