# Generated by Django 5.2.7 on 2025-12-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albummodel',
            name='albumaccess',
            field=models.CharField(choices=[('public', 'pub'), ('private', 'pvt')], default='private', max_length=10),
        ),
    ]
